### ISSUE TITLE
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

### ISSUE THREAD

**Issue by rlacjfjin** [JeonHyeongJunKW/warehouse-simulator#1]
Hi,
When I run the code, I have met with such error:
     AttributeError: 'ForkAwareLocal' object has no attribute 'connection'

I run the code in pycharm with python3.10, could you help me?

Thanks,
Zhe

**Comment by rlacjfjin** [comment]
Hi,
If I add join method after start method in multiprocessing, as following:
        order_maker.start()
        warehouse_tsp_solver.start()
        warehouse_fast_solver.start()
        order_maker.join()
        warehouse_tsp_solver.join()
        warehouse_fast_solver.join()

There is no error but I can't get result even run 2 hours in my notebook.
How can I use this project?
Thanks.

**Comment by rlacjfjin** [comment]
Sorry,
I solved this problem.

Thanks.
Zhe

**Comment by JeonHyeongJunKW** [comment]
OK good!
